[build]
  command = "yarn run build"
  publish = "dist"
  
[template.environment]
  HUGO_VERSION = "0.31.1"
  YARN_VERSION = "1.3.2"

[context.production.environment]
  HUGO_VERSION = "0.31.1"
  YARN_VERSION = "1.3.2"

[context.deploy-preview]
  command = "yarn run build-preview"
